server:
  port: 8888
spring:
  application:
    name: selmag-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/p0stal-ru/test_config.git
          clone-on-start: true
          default-label: master
          search-paths:
            - '{application}/{profile}'